### PR TITLE
update extension docs on ACS characters

### PR DESCRIPTION
**Pull request by GitMensch**
This is the result after trying to come up with a portable use of ACS defines, then checking PDCurses, PDCursesMod and ncurses docs. I _think_ I have this right, but am not sure, so PR.

Additional: maybe this should go into a portability sheet like we have for the functions?

### CODE REVIEW

**Comment by Bill-Gray** [comment]
Interesting.  I'd not realized that ncurses had double-line box characters of any sort,  wide or narrow.  (My guess is that it didn't at the time I wrote the original comment.  Though it's possible that it did,  and I just didn't notice.)

I also see that while the comment implies that we have aliases such as `WACS_BDDB` (for `WACS_D_ULCORNER`),  we don't actually have them.   ncurses does.  Should be easy to fix.  PDCursesMod should  also have (for example) `ACS_SBSD` as an alias for `ACS_SD_RTEE`.

Agreed that a table resembling those for functions,  listing each `ACS_` or `WACS_` and its availability in PDCurses,  PDCursesMod,  ncurses,  and in the "original" Curses specifications would be a good idea.

**Comment by GitMensch** [comment]
The ncurses wide ones are in since only at least 21 years - [ncurses 5.3](https://github.com/mirror/ncurses/commit/46722468f47c2b77b3987729b4bcf2321cccfd01#diff-4716e37395c838b11ecb8f6d18fbf4ae2826d82350b988df434be65f7027709c)

Good that you've spotted some of the ncurses compatibility defines we miss.

Feel free to take directly change the header with a possibly better comment while adding those, so we can close this PR.

**Comment by Bill-Gray** [comment]
> The ncurses wide ones are in since only at least 21 years

And I must have known _something_ about them,  because I set up `testcurs` to show them when compiled with ncurses.

I'll do a "proper" revision of this.  Might be a few days to a week before I get to it.

**Comment by Bill-Gray** [comment]
Done,  with commit e8f7b33bbf35babfc13594cf2be86807b015f9e7.  As you'll see,  I wound up doing some rearranging to put the box characters all together,  with their alias interspersed.  That enabled me to come up with passably clear wording for the various compatibility classes ('standard',  PDCursesMod only,  and PDCursesMod/ncurses only).

**Pull request closed without merging**
