### PR TITLE
Port #45, #83 (WinGUI DPI awareness) to current master branch.

### PR DESCRIPTION
**Pull request by clangen**
Just like the title says. See #45 and #83 for additional context.

### CODE REVIEW

**Comment by Bill-Gray** [comment]
I think we're good here,  with one minor change needed.  In this bit : 
```c
ifndef USER_DEFAULT_SCREEN_DPI /* defined in newer versions of WinUser.h */
TCHAR PDC_font_name[80];
#define USER_DEFAULT_SCREEN_DPI 96
#endif
```
the definition of `PDC_font_name` should be removed.  It conflicts with a later definition saying it's a 128-element array.  (Which I ran into with MinGW cross-compiling on Linux,  and I see Appveyor is running into problems on OpenWATCOM... you don't see the issue on "current" Windows compilations in which `USER_DEFAULT_SCREEN_DPI` is actually #defined .)

Delete that line,  and I think this is ready to pull... thank you!

**Comment by clangen** [comment]
Oops, looks like remnants of a merge conflict I was working through. Just pushed a change that should fix the issue.

**Comment by GitMensch** [comment]
Can you please combine both commits so we only have one?

**Comment by clangen** [comment]
Sure, just rebased and squashed 'em together, then force pushed.

**Comment by GitMensch** [comment]
Thanks, @Bill-Gray do you want to merge it now and then do the SDL/X11 adjustment?

**Comment by Bill-Gray** [comment]
Just got back here,  and merged this fix.

I looked briefly at SDL2.  It appeared as if the [`SDL_GetDisplayDPI ()`function](https://wiki.libsdl.org/SDL2/SDL_GetDisplayDPI) would neatly fit our needs.  However,  a look at the **WARNING** section makes this seem unlikely.  [Adding HiDPI support for SDL2 has been a goal for @wmcbrine as well](https://github.com/wmcbrine/PDCurses/issues/18).  A bit of searching for a solution suggests it's not all that easy (probably why William hasn't gone ahead and done it).

It doesn't help that I lack an HiDPI display,  so I can't really test anything beyond "it doesn't break my system".

**Pull request merged**
