### PR TITLE
fix newterm functionality for vt platform

### PR DESCRIPTION
**Pull request by okbob**
Move output_fd, input_fd to global space from opaque structure. These variables are necessary before this structure can be created and initialized (newterm can be called before initscr). Use input_fd instead stdin and fileno(input_fd) instead hardcoded STDIN (STDIN_FILENO).

### CODE REVIEW

**Comment by Bill-Gray** [comment]
Hmmm... maybe I'm missing something here (quite likely I am),  but...

I set `SP->opaque->input_fd`  _after_ `initscr()` quite intentionally.  The idea was that during initial setup,  we need (on Windows and DOS) to get our input from the "real" terminal in order to get the screen size.  After that,  once `SP->opaque->input_fd` is set,  we get our input from that source instead.

This does cause me to see one bug (fixed in commit 3a73630b08fc1e4aec9427),  and it also makes me see that in `initscr.c`,  `newterm()` should be the "real" code;  `initscr()` should call `newterm( NULL, NULL, NULL)`,  instead of `newterm()` calling `initscr()` and then setting the input/output fds.

**Comment by okbob** [comment]
po 30. 1. 2023 v 2:49 odesílatel Bill Gray ***@***.***>
napsal:

> Hmmm... maybe I'm missing something here (quite likely I am), but...
>
> I set SP->opaque->input_fd *after* initscr() quite intentionally. The
> idea was that during initial setup, we need (on Windows and DOS) to get our
> input from the "real" terminal in order to get the screen size. After that,
> once SP->opaque->input_fd is set, we get our input from that source
> instead.
>
> This does cause me to see one bug (fixed in commit 3a73630
> <https://github.com/Bill-Gray/PDCursesMod/commit/3a73630b08fc1e4aec9427a5d7143836f06fc446>),
> and it also makes me see that in initscr.c, newterm() should be the
> "real" code; initscr() should call newterm( NULL, NULL, NULL), instead of
> newterm() calling initscr() and then setting the input/output fds.
>

I see inconsistency in the ncurses doc. There is a sentence so initscr can
be called after newterm, but inside initscr (lib_initscr.c) is the newterm
function called with stdout, stdin arguments. newtwrm uses stdout, stdin
when arguments are null. So effectively it is not sensible to call these
functions together because initscr overwrite setting of newterm.

terminal line setting is done in _nc_initscr function that is called from
newterm function.

For my purpose the used input stream should be correctly initialized, that
means so in PDC_reset_prog_mod is correctly used input stream and assigned
input buffer (setbuf is null).
Question: setbuf( input_fd, NULL) should be moved to PDC_reset_prog_mode
from PDC_scr_open

**Comment by GitMensch** [comment]
Why was this closed and empty-pushed from https://github.com/Bill-Gray/PDCursesMod/commit/c318f0acde3429d60f225f7db1f5eed74b540a2b?

**Comment by okbob** [comment]
út 7. 2. 2023 v 11:51 odesílatel Simon Sobisch ***@***.***>
napsal:

> Why was this closed and empty-pushed from c318f0a
> <https://github.com/Bill-Gray/PDCursesMod/commit/c318f0acde3429d60f225f7db1f5eed74b540a2b>
> ?
>

It was due my bad knowledge of  git, I am sorry - I broken my local
repository, and I had to resync it again

I did new PR https://github.com/Bill-Gray/PDCursesMod/pull/278

Pavel

**Pull request closed without merging**
