### PR TITLE
[WINCON/WINGUI/SDL2/VT] Added support for cross compilation for Windows on Arm: Enabled custom CFLAGS. Fix missing prefixes for AR and STRIP

### PR DESCRIPTION
**Pull request by okibcn**
WINCON/WINGUI Makefile improvements/fixes:
- Added _a64 setting for cross-compilation for Windows on Arm.
- Enabled custom CFLAGS by adding flags instead of clearing the CFLAGS variable.
- Fixed missing prefixes to complete the AR and STRIP commands to properly support cross-compiling.

### CODE REVIEW

**Comment by GitMensch** [comment]
LGTM, you _may_ want to try "undo last commit" (locally or on gitpod or _possibly on github codespace [never used that so far]), then adjust the commit message `s/custon/custom/` then commit and force-push.

**Comment by okibcn** [comment]
> LGTM, you _may_ want to try "undo last commit" (locally or on gitpod or _possibly on github codespace [never used that so far]), then adjust the commit message `s/custon/custom/` then commit and force-push.

Interesting. Gitpod seems very powerful.

**Comment by Bill-Gray** [comment]
I don't have an ARM platform,  much less a WinARM one.  (Been meaning to get a Raspberry Pi so I could at least test the first part of the puzzle.)

@okibcn,  I gather you've tried this and it works... that's good enough for me.  I'll hold off for the `s/custom/custon` change and/or others,  then pull when you tell me it's good to go.,  At worst,  we'll hear from somebody with a slightly different configuration and will make further fixes then.

**Comment by okibcn** [comment]
@Bill-Gray, @GitMensch s/custon/custom in commit message done. It should be ready to merge now.

**Review by GitMensch — APPROVED** [review]
No additional comment, that's good to merge.
Can you adjust the other Makefiles, too (at least vt, possibly sdls)?

**Comment by okibcn** [comment]
> No additional comment, that's good to merge. Can you adjust the other Makefiles, too (at least vt, possibly sdls)?

I am not sure SDLs are compatible with LLVM. The Makefile is way different and I haven't validated the Xcompiling toolchain from Linux. Maybe in the future. So far it is validated with WINCON and WINGUI only.

**Comment by GitMensch** [comment]
OK, I'm merging this both with and without, but can you give vt a try?

**Comment by okibcn** [comment]
I have tested SDLx and it can be compiled with LLVM-MinGW without any problem. However, the SDL and SDL_ttf libs are not available for Windows on Arm (WoA). They can be compiled for Windows on Arm using the LLVM-MinGW framework the same way I am doing with PDCursesMod, but it would require also a change in how SDL lib is compiled from sources.

In other words, adapting the SDL Makefile for Windows on Arm went the underlying libs are not yet ready, can be only a partial solution. WINCON and WINGUI don't depend on additional libs, this is why it is easy to compile them directly for WoA.

**Comment by GitMensch** [comment]
Note: the failing CI on Appveyor is related to its artifact upload - the builds themselves are fine.

Thanks for the explanation and test on the sdl ports. I think now everything is covered but the vt one, which shouldn't need any additional libraries and work fine on Windows Terminal on win-arm.

**Comment by okibcn** [comment]
I have been working with the VT before. It can be easily updated. I have also solved the window resize limitation, but that will go into another PR. I can add the WoA for VT within this PR.

Adding a better Xcompiling test for LLVM-MinGW is also possible.

**Comment by GitMensch** [comment]
Sounds good, please do.

**Comment by okibcn** [comment]
> Sounds good, please do.

Done.

**Pull request merged**
