### PR TITLE
allow to specify input, output file in newterm function

### PR DESCRIPTION
**Pull request by okbob**
supersedes #276, #278 where the discussion is

tested against pspg without problems

### CODE REVIEW

**Comment by Bill-Gray** [comment]
Looks good to me... thank you!

**Comment by okbob** [comment]
Thank you very much

**Comment by GitMensch** [comment]
As the changes are mostly in the vt - aren't the others affected, too?
Note @Bill-Gray: Changelog entry is missing in any case.

**Comment by Bill-Gray** [comment]
> As the changes are mostly in the vt - aren't the others affected, too?

Only the VT platform (at least at present) uses `SP->input_fd`. And... just realized... _no_ platform uses `SP->output_fd`.
```
gray@gray-d:~/PDCursesMod$ git grep output_fd
curspriv.h:    FILE *output_fd, *input_fd;
pdcurses/initscr.c:    /* output_fd, input_fd should be initialized before PDC_src_open */
pdcurses/initscr.c:    SP->output_fd = outfd ? outfd : stdout;
```
We declare `SP->output_fd`,  comment on it,  set it,  and... then we never use it.

For the VT platform,  we have some logic in `PDC_get_terminal_fd()` (see `vt/pdcdisp.c`) that says : output goes to `stdout` unless that's been redirected;  if so,  use `stderr`.  Except under Windows,  where (I think) you can't tell if output redirection has happened.

I can't think of what meaning would be ascribed to `SP->output_fd` on non-VT platforms.

Noted about the changelog falling behind.

**Comment by okbob** [comment]
st 4. 10. 2023 v 17:37 odesílatel Bill Gray ***@***.***>
napsal:

> As the changes are mostly in the vt - aren't the others affected, too?
>
> Only the VT platform (at least at present) uses SP->input_fd. And... just
> realized... *no* platform uses SP->output_fd.
>
redirect of stdout is not too common. It can be used only when you want to
redirect to another terminal or for support of multiple terminals. But I
don't know any widely used application that does it.

**Pull request merged**
