### PR TITLE
OpenGL port

### PR DESCRIPTION
**Pull request by juliusikkala**
This is a new port, targeting OpenGL 3.3! I used the SDL2 port as a basis. SDL2 is still used to open the window and deal with input, so those parts of the code have some overlap. SDL_ttf is now always used, regardless of whether PDC_WIDE is on or not.

The reason why I started making this port was that the SDL2 port doesn't cache anything and uses software rendering, which ends up being REALLY slow in a lot of situations, even with new PCs. Furthermore, even on a modest refresh rate, I see very high CPU utilization and hear fans kicking in, on a desktop PC no less! So the impractically high FPS numbers I mention below, translate to lowered CPU utilization in real-world use cases, which reduces power consumption and noise.

Here's a brief overview of what's going on:

* Glyphs are cached into an atlas texture the first time they are seen
    * SDL_ttf is slow, so a lot of performance can be gained by keeping already rendered glyphs
    * The implementation should be quite memory-friendly still; only 1 byte per pixel is used ("alpha channel" only)
    * It's quite robust; the texture atlas can grow automatically when needed, and even deals with running out of space by evicting unused glyphs
    * Here's what it looks like in memory (in newtest, after clicking "Next Ucode pg" a few times):
glyph cache atlas image

* The whole screen is always updated at once, in `PDC_doupdate()`
    * The data needed to render all visible characters is uploaded in bulk, keeping driver overhead low
    * It's done in extremely few draw calls (2 or a bit more if combining chars are used)
    * It's based on instancing instead of typical vertex arrays; the vertex shader actually generates the vertices on the fly, based on instance and vertex IDs (this appeared to be slightly faster than vertex arrays due to 6x memory bandwidth savings)
* There's a new demo program, `benchmark`
    * It fills the screen with characters and changes all colors on every frame, and tries to render as fast as possible
    * The FPS is displayed on screen (hovering around 1000 fps on my PC in a maximized window, while the SDL2 port achieves ~40 fps)
benchmark screenshot, big window
    * And in the default 80x25 window:
benchmark screenshot, small window

* Fullwidth and combining characters are supported!
    * ... though the layouting of the combining characters is naive and sometimes incorrect. Combining characters are currently rendered as regular glyphs that happen to be on separate layers that get composited on top of the root characters.
    * Fullwidth should be fully OK!
Screenshot of newtest
    * Also note how the overflowing italics don't clip in grid edges ;) (though, this is also what causes the underline below italics to overextend somewhat)

* There's a couple of additional, user-adjustable variables related to resizing:
    * In addition to the normal resizing behaviour like in the SDL2 port, stretching, aspect ratio preserving scaling and integer scaling are also available. These modes don't change LINES & COLS when the window is resized, but instead just zoom the viewport.
    * This scaling can be done with either bilinear or nearest-neighbor interpolation
* Adds no additional dependencies over SDL2
    * To avoid having to add GLEW or glad, I just made it load the GL functions manually instead.

I have not tested this on Windows yet, because it's a bit of a hassle for me to get my Windows installation working again... So yeah, the current status is "Works on My Machine™".

### CODE REVIEW

**Comment by GitMensch** [comment]
That looks quite nice! Question: could you move out the benchmark addition to a separate PR, adding it to be build on all platforms (mind both CMakelist and Makefiles, please)?
This way we could easily check where we currently are with separate ports and it would make this PR a bit smaller.

**Comment by Bill-Gray** [comment]
This looks promising.  I do,  of course,   appreciate the "works on my machine" caveat.

I'll mention that we do have a speed benchmarking program,  called (oddly enough) `speed`.  You'll notice that the results for most platforms aren't much better than they are for SDL2.  ncurses and VT are fast.  The framebuffer ports,  which aren't listed there because I added them later,  aren't too bad,  somewhere around 600 frames/second.  But I digress.

We already had a good bit of overlap between SDL1 and SDL2,  causing me to think that some bits might get pulled into the `common` directory to avoid code duplication.  This may give us some added incentive to do that.

If you'll forgive a possibly dumb question : I'm wondering if this could simply replace the existing SDL2  port?  The only real drawback of this SDL2/OpenGL port is that you can't do stuff with the window.  I don't see that as a major difficulty.  Other than that,  would there be any reason to keep the existing SDL2 port if we had this one available?

**Comment by juliusikkala** [comment]
Whoops, I somehow managed to completely miss the existence of that `speed` testing program. This port got around 5300-5800 fps in it on my PC. From my point of view, it's a good enough benchmark, so I can just delete the one I added and go with `speed` instead, unless you guys would like to keep `benchmark` for some reason. The only additional thing that would've been nice to have in `speed` is testing color performance as well. The color pair switching incurs some extra overhead which may (or may not) be interesting.

Regarding the overlap; yeah, since SDL2 can be used in conjunction with various graphics APIs (DirectX, OpenGL, Vulkan, Metal, SDL_Surface, SDL_Renderer), which all share the same basic window and input handling, there's a lot of stuff that would be reasonable to refactor into `common`. Not that I'd be particularly interested in implementing further APIs myself, but in case someone else wants to do a DirectX port in the future when they ship their roguelike game on Xbox or something...

The SDL2 replacement question doesn't sound "dumb" to me at all. Here's what I think of it:
**Pros**:
+ Significantly better performance
+ Working fullwidth & combining chars
+ Current SDL2 port is in a weird position due to using the software rendering API, which is a carryover from SDL1

**Cons**:
- OpenGL 3.3 limits platforms
    - Requires a GPU that's newer than about 15 years old (or software impl like llvmpipe)
    - Apple has deprecated their OpenGL support to push their Apple-specific Metal API -.- Losing Macintosh support in SDL2 port could be a big deal for someone
- Can't easily integrate as part of a graphical program like the SDL2 port, existing users would have no workaround other than SDL1
    - Telling them to just use SDL1 instead if they want to do `SDL_Surface` trickery might not be the best idea, since SDL1 was deprecated many years ago.

**Comment by Bill-Gray** [comment]
Coming back to this after a gap of a couple of months...

It sounds to me as if we should,  at least for the nonce,  maintain the "legacy" SDL2 port,  for the reasons you mention and for one more : that port is thoroughly tested and stable,  and we could add the OpenGL port with suitable caveats.  Once pulled,  we could think about separating out the bits that SDL1,  SDL2,  and OpenGL have in common,  and might eventually drop SDL2.

If this port fails on some systems... well,  people will still have "traditional" SDL2;  they won't be any worse off than they already were.

So my inclination is to pull this and see what happens.  Are there changes you think ought to be made before doing so,  or do you consider it ready to go?  (And I'd be interested to hear any comments by anyone else who has given this a try...)

**Comment by GitMensch** [comment]
The one thing I've spotted (and would prefer in a separate PR, but that's not necessarily needed if that gets pulled in soon) is to add the benchmark demo to the other makefiles, check that it works, and give a table that include the results with the different ports.

**Comment by juliusikkala** [comment]
If it's OK to keep the new benchmark demo in this PR, then I consider it ready. I haven't found any issues or features I'd like to add in the few months I've been using this. Though, my use case is a bit limited. I'm a tad bit busy this weekend, so I probably can't find the time to rip it out into a separate PR or do the result table etc. until some time next week.

**Comment by Bill-Gray** [comment]
Re keeping the benchmarking demo : am I correct in thinking this doesn't add anything over the existing `speed` benchmarking program?  (`speed` did lack color output,  but that's been changed.)

If it does add something New and Different,  either `speed` should be made obsolete or the bits from the new program should be added to it.  I don't see a reason to have two such programs.

**Comment by GitMensch** [comment]
I wanted to review the speed test, but the Appveyor binary don't include them - can you please add it to the CMakelists.txt (duplicating the tuidemo entry)?
Does the speedemo contain an FPS counter like the benchmark or would this be part of the things to include?

**Comment by Bill-Gray** [comment]
Turns out the CMakeLists.txt files leave out _many_ demos.  Commit 4f3dc9643601d0376 fixes this for DOS,  DOSVGA, WinCon,  and WinGUI.  Others will follow after I see what AppVeyor thinks of it all,  but should be quite straightforward.

For 'traditional' makefiles,  we have .mif (Make Include Files,  I think) such as those in `common/libobjs.mif` and `common/watcom.mif`.  I think that before I proceed to modify the other CMakeLists,  I'll see if such a thing exists for CMake,  thereby sparing us the need to modify every single one of the censored things each time the list of demos changes.

**Comment by Bill-Gray** [comment]
Forgot to add : `speed` runs for three seconds,  blasting up frames continuously,  then takes the number displayed and divides by three.  So yes,  it shows frames per second.

If you look at the source (`demos/speed.c`),  you'll see a table of results at the top.  It goes back a few years,  to a machine I no longer have.  So it omits,  for example,  the Linux framebuffer and DRM (Direct Rendering Manager) ports.  (Which are very fast).

Comparisons are difficult in any case.  I ran the tests on a Linux box;  the Windows code was tested with Wine and the DOS code in DOSBox,  so the results for those platforms might be better or worse than they would be on native systems.  The DOSVGA code ran a _lot_ faster in 32-bit mode than in 16.  And so on.

A final point : with rare exceptions,  all the ports generate far more frames per second than you can actually view.  Unless you're running on very old hardware (which is a use case for PDCurses/PDCursesMod),  it'd usually be difficult to use up much CPU in displaying,  say,  30 frames per second.  I was (and am) curious about just how fast these ports are,  which is why I wrote `speed`.  But I can't say it's usually a real-world consideration.

**Comment by GitMensch** [comment]
As far as I see the benchmark doesn't seem to add anything over the updated speed demo. In this case it should be dropped. @juliusikkala Do you agree and could adjust, then force-push? In any case it would be useful to rebase.

**Comment by juliusikkala** [comment]
Yeah, I agree. I finally have some time to spend on this, so I'll do it today.

**Comment by juliusikkala** [comment]
Okay, I've now removed the benchmark and rebased on the current state of the master branch.

**Comment by GitMensch** [comment]
Thank you!
@Bill-Gray: do you prefer a single (squash) commit or are those multiple ones fine for you?

**Comment by Bill-Gray** [comment]
I'd just as soon keep the history unsquashed.

As mentioned before,  I'm perfectly content to pull this first and test on machines other than Julius' later,  because it doesn't impact existing platforms.  If you expect to be trying it out,  I'll hold off for your review.  Otherwise,  let's pull it.

**Comment by GitMensch** [comment]
I've clicked merge :-) Big thanks to @juliusikkala for the work on this and the additional adjustments and thanks @Bill-Gray for updating HISTORY after possibly a bit of curses.h adjustment :-)

Just out of interest @juliusikkala: how many FPS do you get with the SDL2 port and how many with the OpenGL one, using the general speed demo?

**Comment by Bill-Gray** [comment]
@juliusikkala,  let me add my thanks as well.  I am currently deeply involved with determining orbits for sungrazing comets (long story),  but should catch up on the history end of this in a bit...

**Comment by juliusikkala** [comment]
Great to have it merged, thanks to you both as well! @GitMensch with `speed` using the default font size, I got 360 fps for SDL2 and 5718 fps for GL. SDL2 is also more sensitive to font size: with `PDC_FONT_SIZE=64`, SDL2 gets 59 fps and GL gets 2646 fps.

**Comment by Bill-Gray** [comment]
I'm getting:

GL (8-bit) : 60 fps
GL (wide) : 60 fps
SDL2 (8-bit): 1500 fps
SDL2 (wide): 380 fps
SDL1 (8-bit): 500 fps
SDL1 (wide): 270 fps
X11 (wide): 900 fps
VT (both wide and 8-bit): 1900 fps
WinGUI (both wide and 8-bit): 370 fps

I have a fairly generic,  low-end graphics card,  and it could be that GL struggles with it.  The WinGUI tests were under Wine;  as noted above,  that might make it either faster or slower than it would be in Microsoft Windows (the speed difference really can go either way).

**Comment by juliusikkala** [comment]
@Bill-Gray Hmm, 60 sounds very suspicious. That's typically what vertical synchronization limits the framerate to, so I think that that is somehow enabled in your case. It makes the program wait for screen refreshes in `SDL_GL_SwapWindow`. That should definitely be disabled for this use case since we don't push frames on a constant rate like that.

`SDL_GL_SetSwapInterval(0);` was supposed to disable it though... Unless you have it force-enabled from your GPU settings, I don't know what's causing this. If you have an Nvidia card, you can find it as "Sync to VBlank" under OpenGL settings. If it's not that, I'd open an issue about this, it can't really be that slow and the exact 60 would point to the vsync being the case.

Can you try measuring how long this line takes to run? https://github.com/Bill-Gray/PDCursesMod/blob/52a2fdf518d29fe80078fa1a18afd91c3831cb15/gl/pdcdisp.c#L906 if it's in the range of 10-16 milliseconds, the culprit is very likely vsync.

**Comment by Bill-Gray** [comment]
@juliusikkala - Thanks for digging into this.   First,  I should note that I'm using an nVidia card under Linux with the open-source nouveau driver,  so lack of sterling performance is unsurprising.  Insert standard complaints about nVidia here.

Actually,  in view of this,  I'm kinda surprised I'm getting such good performance in X11,  SDLn,  etc.    `lspci` tells us that I have
```
VGA compatible controller: NVIDIA Corporation GF116 [GeForce GTX 550 Ti] (rev a1)
```
Still,  I'd think that in theory,  some tweaking might get GL performance that was in the ballpark of what I see on the SDLn,  X11,  etc. platforms.

 `SDL_GL_SetSwapInterval( )` returns -1,  with `SDL_GetError( )` then saying "That operation is not supported".  With the default font size,  I always get 59 or 60 frames/second. 

Still with the default font,  `SDL_GL_SwapWindow()` takes five or six milliseconds.  `PDC_doupdate()` in its entirety takes ~9 ms.

However, `export PDC_FONT_SIZE=10` gets me 83 fps.  `export PDC_FONT_SIZE=4` brings that up to 97 fps.   `export PDC_FONT_SIZE=36` drops me down to 30 fps.

**Comment by Bill-Gray** [comment]
@juliusikkala - true,  I don't know how many people are using nouveau.  I've found it to be perfectly acceptable for my humble needs,  but then again,  I'm not doing anything heavy-duty in the graphics department.  I assume that nobody on Windows would ever know this issue existed.
> A more desperate measure would be trying SDL_GL_SetAttribute(SDL_GL_ACCELERATED_VISUAL, 0); to try to force software rendering, but that would need to be conditionally enabled when the driver is known to be "bad".

I gave it a try (line should go just before `SDL_GL_CreateContext()`,  correct?).  No effect on speed.  (Which may mean that acceleration simply isn't available,  so disabling it didn't do anything.)  Similarly,  no change when adding the double-buffering line,  or when adding both lines.

I was going to say that this all may not matter much;  people who run into speed issues with one port can just use the other.  But that's a pain when you're attempting to supply compiled software and not just building everything on your own machine.

**Comment by juliusikkala** [comment]
@Bill-Gray Yeah, the last point is a bit of a concern for me too. I may need to send binaries over to other people at some point, and I can't really know whether they're using nouveau or not.

I got an idea for a performance improvement though. We could optionally decouple rendering to an alternate thread, which just renders the latest state at a steady rate (preferrably at screen refresh rate). This would get rid of tearing and decouple rendering performance from PDC_doupdate(), likely at the cost of additional input delay. It will require some juggling because OpenGL contexts can only be used from one thread at a time. I think I'll try it out this weekend and open a PR if it works out.

**Comment by GitMensch** [comment]
> I may need to send binaries over to other people at some point, and I can't really know whether they're using nouveau or not.

This is relative easy to solve: build and distribute both the OpenGL and the SDL2 port as shared libraries and distribute both (possible in sub-directories). Then either an install procedure for the binaries copies the "right" one in the install directory or the user would take the right one with `LD_LIBRARY_PATH` - you can, for example, provide two start scripts - one would set the first one, the other the second, then start the application.

**Pull request merged**
