### PR TITLE
newterm allow to set input stream

### PR DESCRIPTION
**Pull request by okbob**
supersedes #276, where the discussion is

### CODE REVIEW

**Comment by GitMensch** [comment]
ping @Bill-Gray where this should go (if that should be added then we can fix the merge conflicts)

**Comment by Bill-Gray** [comment]
Returning to this... looks as if it should be more straightforward than it was.  (And it already was somewhat straightforward,  more so than I appreciated at the time.)

It helps that we no longer have the `opaque` structure.  Parameters such as `SP->opaque->output_fd` are simply `SP->output_fd`,  and so forth.  So I don't think _any_ of the changes @okbob had to do for `color.c` are needed now;   we don't have to mess about with allocating/deallocating the `opaque` structure. 

I set (what are now) `SP->output_fd` and `SP->input_fd` _after_ calling `PDC_scr_open()`.  That's because I had input file redirection in mind.  In that case,  you want screen initialization to be done with `stdin` and `stdout` at first,  so that you read the screen size and other responses from the terminal.   Only after that would you use the file pointers passed to `newterm()`.

But when working with another terminal,  you'd want the order reversed,  the way it is in this pull request (and I think `newterm()` is mostly intended to work that way).

That would (I think) require nothing more than moving these two lines : 
```c
     SP->output_fd  = outfd;
     SP->input_fd = infd;
```
(in `newterm()`) up a bit within the function,  to just above the call to `PDC_scr_open()`.  I think that's the only thing that has to be done now in `initscr.c` (again,  things were slightly more complicated back when @okbob first did this.)

We might want to add a function such as
`PDC_reset_fds( SCREEN *sp, FILE *input_fd, FILE *output_fd);`
to be called after `initscr()` or `newterm()` if you actually want the input/output files to be stdin/stdout during screen initialization,  but to then be modified.  Not sure if that's apt to be a requested feature,  though.

I think the logic within the `vt` platform will be largely as this pull request has it,  with some minor simplifications possible due to no longer having the `opaque` struct.

**Comment by okbob** [comment]
do you prepare a patch or I should to do it?

**Comment by Bill-Gray** [comment]
I'm afraid I probably won't get to it in a week or so.  I'll be happy to do it then,  but if you get to it first,  I won't mind that either.  (I'd basically just be implementing the above -- no changes to `color.c`,  move two lines in `initscr.c`,  and tweaking what you did for `pdcscrn.c` and `pdckbd.c`... most of the time will be spent testing to make sure I didn't break anything... actually,  if you have code already using this feature,  you're a couple of steps ahead of me on being able to test,  and I'd appreciate you doing it.)

**Comment by okbob** [comment]
https://github.com/Bill-Gray/PDCursesMod/pull/303

**Comment by okbob** [comment]
replaced by https://github.com/Bill-Gray/PDCursesMod/pull/303

**Pull request closed without merging**
